# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python Learning\CZXD5\CZXD5.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 422)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 421))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python Learning\\CZXD5\\background.jpeg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 221, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:pink;\n"
"font-family:微软雅黑;\n"
"font-size:36px;")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 120, 511, 41))
        self.lineEdit.setStyleSheet("background-color:skyblue;\n"
"font-family:微软雅黑;\n"
"font-color:pink;\n"
"font-size:24px;")
        self.lineEdit.setMaxLength(1000)
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(30, 200, 481, 41))
        self.progressBar.setStyleSheet("font-size:30px;\n"
"font-family:微软雅黑;\n"
"color:pink;")
        self.progressBar.setProperty("value", 46)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.Send = QtWidgets.QPushButton(Form)
        self.Send.setGeometry(QtCore.QRect(90, 290, 341, 111))
        self.Send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Send.setMouseTracking(True)
        self.Send.setStyleSheet("font-family:楷体;\n"
"font-size:60px;\n"
"background-color:darkblue;\n"
"font-color:white;\n"
"color:white;")
        self.Send.setObjectName("Send")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(460, 390, 54, 12))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        self.Send.clicked.connect(Form.send) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "控制小钉5.0"))
        self.label_2.setText(_translate("Form", "控制小钉5.0"))
        self.lineEdit.setText(_translate("Form", "请输入你要发送的信息"))
        self.Send.setWhatsThis(_translate("Form", "<html><head/><body><p>发送信息</p></body></html>"))
        self.Send.setText(_translate("Form", "点击发送"))
        self.label_3.setText(_translate("Form", "By Wdq"))
