# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python Learning\CZXD\CZXD5\CZXD5.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import requests
import json


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.backGround = QtWidgets.QLabel(Form)
        self.backGround.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.backGround.setText("")
        self.backGround.setPixmap(QtGui.QPixmap("D:\\Python Learning\\CZXD\\CZXD5\\bkgd.jpeg"))
        self.backGround.setObjectName("backGround")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 70, 211, 31))
        self.label.setStyleSheet("color:pink;\n"
                                 "font-family:华文行楷;\n"
                                 "font-size:40px;")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(560, 0, 81, 481))
        self.progressBar.setProperty("value", 80)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(Form)
        self.progressBar_2.setGeometry(QtCore.QRect(0, 0, 81, 481))
        self.progressBar_2.setProperty("value", 80)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(80, 129, 481, 51))
        self.lineEdit.setStyleSheet("background-color:darkblue;\n"
                                    "color:white;\n"
                                    "font-family:微软雅黑;\n"
                                    "font-size:36px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(100, 30, 121, 81))
        self.lcdNumber.setStyleSheet("font-size:56]px;")
        self.lcdNumber.setProperty("value", 2021.1115)
        self.lcdNumber.setProperty("intValue", 2021)
        self.lcdNumber.setObjectName("lcdNumber")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(120, 190, 401, 192))
        self.textBrowser.setStyleSheet("font-family:微软雅黑;\n"
                                       "background-color:skyblue;")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 392, 341, 81))
        self.pushButton.setStyleSheet("font-family:华文行楷;\n"
                                      "font-size:56px;\n"
                                      "background-color:blue;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 30, 75, 81))
        self.pushButton_2.setStyleSheet("font-family:华文行楷;\n"
                                        "font-size:36px;\n"
                                        "background-color:skyblue;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.backGround.raise_()
        self.progressBar.raise_()
        self.progressBar_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lcdNumber.raise_()
        self.textBrowser.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)  # type: ignore
        self.pushButton_2.clicked.connect(self.textBrowser.clear)  # type: ignore
        self.lineEdit.textEdited['QString'].connect(self.pushButton.hide)  # type: ignore
        self.lineEdit.editingFinished.connect(self.pushButton.show)  # type: ignore
        self.pushButton_2.clicked.connect(self.lcdNumber.hide)  # type: ignore
        self.lineEdit.textEdited['QString'].connect(self.lcdNumber.hide)  # type: ignore
        self.lineEdit.textEdited['QString'].connect(self.textBrowser.insertPlainText)  # type: ignore
        self.pushButton_2.clicked.connect(self.label.hide)  # type: ignore
        self.pushButton.released.connect(self.lineEdit.clear)  # type: ignore
        self.pushButton.pressed.connect(Form.send)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setProperty("控制小钉5.1", _translate("Form", "Form"))
        self.label.setText(_translate("Form", "控制小钉5.1"))
        self.lineEdit.setText(_translate("Form", "请在这里输入文字"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已发送列表:</p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Form", "发送"))
        self.pushButton_2.setText(_translate("Form", "清空"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
